name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.0
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Netension_covider" /n:"Covider" /o:"netension" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vstest.reportsPaths=".\TestResults\*.trx" /d:sonar.cs.opencover.reportsPaths=".\TestResults\**\*.opencover.xml" /d:sonar.host.url="https://sonarcloud.io"
          dotnet restore --no-cache .\src\Netension.Covider.sln
          dotnet build --configuration Release .\src\Netension.Covider.sln
          
          dotnet test --blame --configuration Release --results-directory ".\TestResults\" --logger "trx;LogFileName=Unit.trx" --collect:"XPlat Code Coverage" .\src\Netension.Covider.Test.Unit\Netension.Covider.Test.Unit.csproj -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          dotnet test --blame --configuration Release --results-directory ".\TestResults\" --logger "trx;LogFileName=Integration.trx" --collect:"XPlat Code Coverage" .\src\Netension.Covider.Test.Integration\Netension.Covider.Test.Integration.csproj -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        
      
